Config / meta.yml
 Meta_title: "DeskJoy"
 Meta_description: "Find Workspace Within Your Industry, find great places to work with local experts."
 Meta_image: "logo.png" # An image in your folder app / assets / images /
 Twitter_account: "@nomdevaccount" # indispensable for Twitter Cards
